# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a5fbfaf3ba795a7a29aa6dce42dbb1c9c5b4308baf98f21ef1201ebd85580648111ac4c75fb6fb3729519f7b9887a9f38c7f210c594e5ebb4d7ae27edc2a184

test:
  secret_key_base: 7d0e80f8465e12d84e70baf4cd1a8cfe56d603505d6b8702efdbabf9023ae19a029247ba5fff0e508d7d8f1fc291b960746995ff78a4dfd5f69574a839d79a02

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
